name: 📦 Build Flatpak

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: build-flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configure GPG Key
      run: |
        echo -n "$GPG_SIGNING_KEY" | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SECRET_KEY }}
    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: io.github.suntorytimed.camunda-modeler.flatpak
        manifest-path: io.github.suntorytimed.camunda-modeler.yaml
        cache-key: flatpak-builder-${{ github.sha }}
        gpg-sign: ${{ secrets.GPG_KEY }}
    - name: Deploy
      if: github.event_name != 'pull_request'
      uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
      with:
        repository: ""
        flat-manager-url: https://flatpak.hibiki.eu
        token: ${{ secrets.FLATMAN_TOKEN }}
