name: 📦 Build Flatpaks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: Build flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configure GPG Key
      if: github.event_name != 'pull_request'
      run: |
        echo -n "$GPG_SIGNING_KEY" | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SECRET_KEY }}
    - name: Build Test Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      if: github.event_name == 'pull_request'
      with:
        bundle: io.github.suntorytimed.camunda-modeler.flatpak
        manifest-path: io.github.suntorytimed.camunda-modeler.yaml
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Build Release Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      if: github.event_name != 'pull_request'
      with:
        bundle: io.github.suntorytimed.camunda-modeler.flatpak
        manifest-path: io.github.suntorytimed.camunda-modeler.yaml
        cache-key: flatpak-builder-${{ github.sha }}
        gpg-sign: ${{ secrets.GPG_KEY }}
    - name: Deploy
      if: github.event_name != 'pull_request'
      uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
      with:
        repository: ""
        flat-manager-url: https://flatpak.hibiki.eu
        token: ${{ secrets.FLATMAN_TOKEN }}
  plugin:
    name: Build plugin
    needs: flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configure GPG signing key
      if: github.event_name != 'pull_request'
      run: |
        echo -n "$GPG_SIGNING_KEY" | gpg --import
        echo -n "$GPG_KEY" | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SECRET_KEY }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
    - name: Configure GPG public key
      run: |
        echo -n "$GPG_KEY" | gpg --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
    - name: Build Plugin Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      if: github.event_name == 'pull_request'
      with:
        bundle: io.github.suntorytimed.Plugin.camunda-modeler-token-simulation.flatpak
        manifest-path: io.github.suntorytimed.Plugin.camunda-modeler-token-simulation.yaml
        repository-name: HibikiEU
        repository-url: https://flatpak.hibiki.eu/repo/hibiki.flatpakrepo
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Build Release Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      if: github.event_name != 'pull_request'
      with:
        bundle: io.github.suntorytimed.Plugin.camunda-modeler-token-simulation.flatpak
        manifest-path: io.github.suntorytimed.Plugin.camunda-modeler-token-simulation.yaml
        repository-name: HibikiEU
        repository-url: https://flatpak.hibiki.eu/repo/hibiki.flatpakrepo
        cache-key: flatpak-builder-${{ github.sha }}
        gpg-sign: ${{ secrets.GPG_KEY }}
    - name: Deploy
      if: github.event_name != 'pull_request'
      uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
      with:
        repository: ""
        flat-manager-url: https://flatpak.hibiki.eu
        token: ${{ secrets.FLATMAN_TOKEN }}
